/* Ian da Silva Correia
 * ADS 2021-2
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadExtra extends javax.swing.JFrame {

    private Extra foneext;
    private BDExtra BDExt = new BDExtra();
    private static CadExtra unicoCadExtra;
    
    /**
     * Creates new form FramePrincipal
     */
    private CadExtra() {
        initComponents();
    }
    
    public static CadExtra getCadExtra(){
        if(unicoCadExtra == null){
            unicoCadExtra = new CadExtra();
        }
        return unicoCadExtra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelPreco = new javax.swing.JLabel();
        labelMarca = new javax.swing.JLabel();
        ctID = new javax.swing.JTextField();
        ctPreco = new javax.swing.JTextField();
        ctMarca = new javax.swing.JTextField();
        ctArco = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaExtra = new javax.swing.JTable();
        labelEntrada = new javax.swing.JLabel();
        menuJanela = new javax.swing.JMenuBar();
        MenuFIle = new javax.swing.JMenu();
        MenuTipos = new javax.swing.JMenu();
        opIntra = new javax.swing.JMenuItem();
        opSupra = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setText("Cadastrar Fones Extra-Auriculares");
        titulo.setAutoscrolls(true);
        titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelID.setText("ID-Produto");

        labelPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPreco.setText("Preço do Produto");

        labelMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMarca.setText("Marca do Produto");

        ctID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctIDActionPerformed(evt);
            }
        });

        ctMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctMarcaActionPerformed(evt);
            }
        });

        ctArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctArcoActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btApagar.setText("Apagar");
        btApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarActionPerformed(evt);
            }
        });

        tabelaExtra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID-Produto", "Preço", "Marca", "Tipo de Entrada"
            }
        ));
        jScrollPane1.setViewportView(tabelaExtra);

        labelEntrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEntrada.setText("Tamanho do arco");

        MenuFIle.setText("Opções");

        MenuTipos.setText("Tipos");

        opIntra.setText("Intra Auriculares");
        opIntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIntraActionPerformed(evt);
            }
        });
        MenuTipos.add(opIntra);

        opSupra.setText("Supra Auriculares");
        opSupra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSupraActionPerformed(evt);
            }
        });
        MenuTipos.add(opSupra);

        MenuFIle.add(MenuTipos);
        MenuFIle.add(jSeparator1);

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        MenuFIle.add(MenuSair);

        menuJanela.add(MenuFIle);

        setJMenuBar(menuJanela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPreco)
                    .addComponent(labelMarca)
                    .addComponent(labelID)
                    .addComponent(labelEntrada)
                    .addComponent(titulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ctArco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addComponent(ctMarca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ctPreco, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ctID, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btApagar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(labelPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctArco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCadastrar)
                            .addComponent(btConsultar)
                            .addComponent(btAlterar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btApagar)
                            .addComponent(btLimpar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctIDActionPerformed

    private void ctMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctMarcaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void ctArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctArcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctArcoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrarfoneext();
        listarTabela();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // TODO add your handling code here:
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        alterar();
        listarTabela();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarActionPerformed
        // TODO add your handling code here:
        apagar();
        listarTabela();
    }//GEN-LAST:event_btApagarActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_MenuSairActionPerformed

    private void opIntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIntraActionPerformed
        // TODO add your handling code here:
        CadInt.getCadInt().setVisible(true);
    }//GEN-LAST:event_opIntraActionPerformed

    private void opSupraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSupraActionPerformed
        // TODO add your handling code here:
        CadSupra.getCadSupra().setVisible(true);
    }//GEN-LAST:event_opSupraActionPerformed

    public void apagar(){
        foneext = new Extra();
        try{
            foneext.setIdProduto(Integer.parseInt(ctID.getText()));
            foneext = BDExt.consultaIDExtra(foneext);
        
            if(foneext != null){
                ctID.setText(Integer.toString(foneext.getIdProduto()));
                ctPreco.setText(Float.toString(foneext.getPreco()));
                ctMarca.setText(foneext.getMarca());
                ctArco.setText(Integer.toString(foneext.getTamanhoArco()));
                int x = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse Produto do Banco de dados?", "Exclusão", JOptionPane.YES_NO_OPTION);
                if(x == 0){
                    BDExt.apagarBDExt(foneext);
                    JOptionPane.showMessageDialog(null, "Produto apagado com sucesso!", "Sucesso!", JOptionPane.DEFAULT_OPTION);
                    limpar();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Não foi encontrado um produto com esse ID!", "ERRO", JOptionPane.ERROR_MESSAGE);
                limpar();
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "O ID só deve ser do tipo inteiro!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    public void alterar(){
        foneext = new Extra();
        try{
            foneext.setIdProduto(Integer.parseInt(ctID.getText()));
            foneext = BDExt.alterarBDExt(foneext);
        
            if(foneext != null){
                ctID.setText(Integer.toString(foneext.getIdProduto()));
                ctPreco.setText(Float.toString(foneext.getPreco()));
                ctMarca.setText(foneext.getMarca());
                ctArco.setText(Integer.toString(foneext.getTamanhoArco()));
                JOptionPane.showMessageDialog(null, "Dados atualizados!.", "Sucesso!", JOptionPane.DEFAULT_OPTION);
                limpar();
            }else{
                JOptionPane.showMessageDialog(null, "Não foi encontrado um produto com esse ID!", "ERRO", JOptionPane.ERROR_MESSAGE);
                limpar();
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "O ID só deve ser do tipo inteiro!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    public void listarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaExtra.getModel();
        int indice = 0;
        
        modelo.setRowCount(indice);
        for(Extra foneext : BDExt.getBDExt()){
            modelo.insertRow(indice, new Object[]{foneext.getIdProduto(), foneext.getPreco(), foneext.getMarca(), foneext.getTamanhoArco()});
            indice++;
        }
    }
    
    public void consultar(){
        foneext = new Extra();
        try{
            foneext.setIdProduto(Integer.parseInt(ctID.getText()));
            foneext = BDExt.consultaIDExtra(foneext);
        
            if(foneext != null){
                ctID.setText(Integer.toString(foneext.getIdProduto()));
                ctPreco.setText(Float.toString(foneext.getPreco()));
                ctMarca.setText(foneext.getMarca());
                ctArco.setText(Integer.toString(foneext.getTamanhoArco()));
                JOptionPane.showMessageDialog(null, "Confira os dados.", "Encontrado!", JOptionPane.DEFAULT_OPTION);
            }else{
                JOptionPane.showMessageDialog(null, "Não foi encontrado um produto com esse ID!", "ERRO", JOptionPane.ERROR_MESSAGE);
                limpar();
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "O ID só deve ser do tipo inteiro!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void cadastrarfoneext(){
        foneext = new Extra();
        try {
            foneext.setPreco(Float.parseFloat(ctPreco.getText()));
            foneext.setIdProduto(Integer.parseInt(ctID.getText()));
            foneext.setMarca(ctMarca.getText());
            foneext.setTamanhoArco(Integer.parseInt(ctArco.getText()));
            
            
            foneext = BDExt.setBDExt(foneext);
            if(foneext != null){
                JOptionPane.showMessageDialog(null, "Cadastrado feito corretamente.", "Sucesso", JOptionPane.DEFAULT_OPTION);
                limpar();
            }else{
                JOptionPane.showMessageDialog(null, "Ja existe um fone com esse ID!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(PrecoException ex){
            JOptionPane.showMessageDialog(null, "Preencha os valores corretamente", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void limpar(){
        ctID.setText("");
        ctPreco.setText("");
        ctMarca.setText("");
        ctArco.setText("");
        ctID.requestFocus();
    }
    
    public void sair(){
           int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "SAIR?", JOptionPane.YES_NO_OPTION);
           if (resposta ==0){
               this.dispose();
           }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFIle;
    private javax.swing.JMenuItem MenuSair;
    private javax.swing.JMenu MenuTipos;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField ctArco;
    private javax.swing.JTextField ctID;
    private javax.swing.JTextField ctMarca;
    private javax.swing.JTextField ctPreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelEntrada;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JMenuBar menuJanela;
    private javax.swing.JMenuItem opIntra;
    private javax.swing.JMenuItem opSupra;
    private javax.swing.JTable tabelaExtra;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
